---
- name: TOWER-AS3-BIG-IQ - Application Service
  hosts: bigiq
  connection: local
  gather_facts: false

  tasks:

    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    - name: Authenticate to BIG-IQ
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/authn/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          loginProviderName: RadiusServer
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth
      
    - name: Validate AS3 Rest Worker is ready
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/appsvcs/declare"
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        validate_certs: false
      retries: 30
      delay: 5
      register: result
      until: "(result is success) and (result.status == 200)"

    - name: Send AS3 Declaration - POST /mgmt/shared/appsvcs/declare?async=true
      uri:
        url: https://{{ mgmt }}/mgmt/shared/appsvcs/declare?async=true
        method: POST
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        body: "{{ lookup('template','j2/'+app_type+'.j2') }}"
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: json_response

    - pause:
        seconds: 15

    ## LOOP TO CHECK THE TASK

    - name: LOOP Check AS3 Deployment Task - GET /mgmt/shared/appsvcs/task/<task_id>
      uri:
        url: https://{{ mgmt }}/mgmt/shared/appsvcs/task/{{json_response.json.id}}
        method: GET
        headers:
          Content-Type: application/json
          X-F5-Auth-Token: "{{auth.json.token.token}}"
        status_code: 200, 202
        validate_certs: false
      register: json_response_task
      until: "json_response_task.json.results[0].message != 'in progress'"
      retries: 20
      delay: 10

    - debug:
        var: json_response_task.json