---
- name: TOWER-AS3-BIG-IQ - CREATE AND ONBOARD BIG-IP on BIG-IQ
  hosts: bigiq
  connection: local
  gather_facts: false
  vars:
    GCE_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"
    GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
    GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
    onboard_log: "/var/log/startup-script.log"
    libs_dir: "/config/cloud/google"
    AS3_URL: "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.16.0/f5-appsvcs-3.16.0-6.noarch.rpm"
    DO_URL: "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.9.0/f5-declarative-onboarding-1.9.0-1.noarch.rpm"
    TS_URL: "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.8.0/f5-telemetry-1.8.0-1.noarch.rpm"
    BIGIP_PASS: "{{ bigip_password }}"

  tasks:
    # First download galaxy roles for F5 ATC
    - name: Install roles from Ansible Galaxy
      command: ansible-galaxy install f5devcentral.atc_deploy -p ./roles/ 

    - name: show downloaded roles
      command: ls ./roles/

    ####################################################
    # Below tasks are for creating a new BIG-IP in GCP #
    ####################################################


    - name: Create a network
      gcp_compute_network:
        name: "{{ resource_prefix }}-network"
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file:  "{{ GCE_CREDENTIALS_FILE_PATH }}"
        auto_create_subnetworks: true
        routing_config:
          routing_mode: REGIONAL
        state: present
      register: gce_network

    - name: Debug network
      debug: var=gce_network

    - name: create a firewall
      gcp_compute_firewall:
        name: "{{ resource_prefix }}-network-fw"
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
              - '443'
              - '8443'
          - ip_protocol: icmp
        network: "{{ gce_network }}"
        direction: INGRESS
        target_tags:
        - bigiq-lab
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        state: present

    - name: create an address
      gcp_compute_address:
        name: '{{ resource_prefix }}-address-instance'
        region: "{{ gcp_region }}"
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address

    # - name: Debug address
    #   debug: var=address

    - name: Set address as var
      set_fact:
        bigip_mgmt: "{{ address.address }}"

    - name: create a disk
      gcp_compute_disk:
        name: '{{ resource_prefix }}-disk-instance'
        size_gb: 80
        source_image: 'projects/f5-7626-networks-public/global/images/f5-bigip-14-1-2-3-0-0-5-byol-all-modules-1boot-loc-19121814223'
        zone: "{{ gcp_zone }}"
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk

    - name: create an instance
      gcp_compute_instance:
          state: present
          name: '{{ resource_prefix }}-bigip-instance'
          machine_type: n1-standard-4
          disks:
            - auto_delete: true
              boot: true
              source: "{{ disk }}"
          network_interfaces:
              - network: "{{ gce_network }}"
                access_configs:
                  - name: 'External NAT'
                    nat_ip: "{{ address }}"
                    type: 'ONE_TO_ONE_NAT'
          zone: "{{ gcp_zone }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          metadata:
            enable-oslogin: "FALSE"
            startup-script: "{{ lookup('template', 'templates/f5_onboard.j2') }}"
          tags:
            items:
              - bigiq-lab
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ bigip_mgmt }} port=22 delay=10 timeout=60

    ###########################################################
    # Below tasks are for onboarding the newly created BIG-IP #
    ###########################################################
    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    # provider var for atc_deploy role
    - name: Set connection provider for BIG-IP tasks
      set_fact:
        provider_atc: 
          server: "{{ bigip_mgmt }}"
          server_port: 8443
          user: "{{ bigip_user }}"
          password: "{{ bigip_password }}"
          validate_certs: false

    - name: prepare the DO declarations
      template: 
        src: "templates/onboard_bigip_do_{{ item.src }}.j2"
        dest: "files/onboard_bigip_do_{{ item.dest }}.json"
      delegate_to: localhost
      when: "{{ requested_modules == item.when }}"
      loop:
        - { src: "ltm", dest: "ltm", when: "ltm" }
        - { src: "asm", dest: "asm", when: "asm" }

    # Use DO to license, provision, and set passwords on new BIG-IP
    # Official galaxy role for F5 automation tool chain (https://galaxy.ansible.com/f5devcentral/atc_deploy)
    - name: ATC POST
      include_role:
        name: f5devcentral.atc_deploy
      vars: 
        provider: "{{ provider_atc }}"
        atc_service: Device
        atc_method: POST
        atc_declaration_file: "{{ lookup('template', 'files/onboard_bigip_do_{{ item.atc_declaration_file }}.json') }}"
        atc_delay: 10
        atc_retries: 10
      when: "{{ requested_modules == item.when }}"
      loop:
        - { atc_declaration_file: "ltm", when: "ltm" }
        - { atc_declaration_file: "asm", when: "asm" }

    # Get authentication token for uri module tasks below
    - name: Authenticate to BIG-IQ
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/authn/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          loginProviderName: local
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    # By default, LTM is provisioned, so adding to the list of modules to discover when registering on BIG-IQ.
    # Also adding in GTM  
    - set_fact:
        provisioned_modules: ['ltm', 'gtm']

    # Note that security_shared is also required here
    - name: Add ASM to list of modules to discover
      set_fact:
        provisioned_modules: "{{ provisioned_modules + ['asm'] + ['security_shared']}}"
      when: requested_modules == "asm"

    - name: Debug provisioned_modules list
      debug: var=provisioned_modules

    # Discover new BIG-IP
    - name: Discover a new BIG-IP device
      bigiq_device_discovery:
        device_address: "{{ bigip_mgmt }}"
        device_username: "{{ bigip_user }}"
        device_password: "{{ bigip_password }}"
        modules: "{{ provisioned_modules }}"
        provider: 
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          server: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}"
          validate_certs: no
      delegate_to: localhost