---
- name: TOWER-AS3-BIG-IQ - CREATE AND ONBOARD BIG-IP on BIG-IQ
  hosts: bigiq
  connection: local
  gather_facts: false
  vars:
    GCE_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"
    GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
    GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"
    onboard_log: "/var/log/startup-script.log"
    libs_dir: "/config/cloud/google"
    AS3_URL: "https://github.com/F5Networks/f5-appsvcs-extension/releases/download/v3.16.0/f5-appsvcs-3.16.0-6.noarch.rpm"
    DO_URL: "https://github.com/F5Networks/f5-declarative-onboarding/releases/download/v1.9.0/f5-declarative-onboarding-1.9.0-1.noarch.rpm"
    TS_URL: "https://github.com/F5Networks/f5-telemetry-streaming/releases/download/v1.8.0/f5-telemetry-1.8.0-1.noarch.rpm"
    BIGIP_PASS: "{{ bigip_password }}"

  tasks:
    # First download galaxy roles for F5 ATC
    - name: Install roles from Ansible Galaxy
      command: ansible-galaxy install f5devcentral.atc_deploy -p ./roles/ 

    - name: show downloaded roles
      command: ls ./roles/

    ####################################################
    # Below tasks are for creating a new BIG-IP in GCP #
    ####################################################


    - name: Create a network
      gcp_compute_network:
        name: "{{ resource_prefix }}-network"
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file:  "{{ GCE_CREDENTIALS_FILE_PATH }}"
        auto_create_subnetworks: true
        routing_config:
          routing_mode: REGIONAL
        state: present
      register: gce_network

    - name: Debug network
      debug: var=gce_network

    - name: create a firewall
      gcp_compute_firewall:
        name: "{{ resource_prefix }}-network-fw"
        allowed:
          - ip_protocol: tcp
            ports:
              - '22'
              - '443'
              - '8443'
          - ip_protocol: icmp
        network: "{{ gce_network }}"
        direction: INGRESS
        target_tags:
        - bigiq-lab
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        state: present

    - name: create an address
      gcp_compute_address:
        name: '{{ resource_prefix }}-address-instance'
        region: "{{ gcp_region }}"
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: address

    # - name: Debug address
    #   debug: var=address

    - name: Set address as var
      set_fact:
        bigip_mgmt: "{{ address.address }}"

    - name: create a disk
      gcp_compute_disk:
        name: '{{ resource_prefix }}-disk-instance'
        size_gb: 80
        source_image: 'projects/f5-7626-networks-public/global/images/f5-bigip-14-1-2-3-0-0-5-byol-all-modules-1boot-loc-19121814223'
        zone: "{{ gcp_zone }}"
        project: "{{ GCE_PROJECT }}"
        auth_kind: serviceaccount
        service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        scopes:
          - https://www.googleapis.com/auth/compute
        state: present
      register: disk

    - name: create an instance
      gcp_compute_instance:
          state: present
          name: '{{ resource_prefix }}-bigip-instance'
          machine_type: n1-standard-4
          disks:
            - auto_delete: true
              boot: true
              source: "{{ disk }}"
          network_interfaces:
              - network: "{{ gce_network }}"
                access_configs:
                  - name: 'External NAT'
                    nat_ip: "{{ address }}"
                    type: 'ONE_TO_ONE_NAT'
          zone: "{{ gcp_zone }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          metadata:
            enable-oslogin: "FALSE"
            startup-script: "{{ lookup('template', 'templates/f5_onboard.j2') }}"
          tags:
            items:
              - bigiq-lab
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ bigip_mgmt }} port=22 delay=10 timeout=60

    ####################################################################
    # Below tasks are for onboarding the newly created BIG-IP on BIG-IQ#
    ####################################################################
    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    # provider var for atc_deploy role, using BIG-IQ
    - name: Set connection provider for BIG-IQ tasks
      set_fact:
        provider_atc: 
          server: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}"
          server_port: 443
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          validate_certs: false

    - name: prepare the DO declarations
      template: 
        src: "templates/onboard_bigip_do_{{ item.src }}.j2"
        dest: "files/onboard_bigip_do_{{ item.dest }}.json"
      delegate_to: localhost
      when: "{{ requested_modules == item.when }}"
      loop:
        - { src: "ltm", dest: "ltm", when: "ltm" }
        - { src: "asm", dest: "asm", when: "asm" }

    # Use DO to license, provision, and discover new BIG-IP on BIG-IQ
    # Official galaxy role for F5 automation tool chain (https://galaxy.ansible.com/f5devcentral/atc_deploy)
    - name: ATC POST
      include_role:
        name: f5devcentral.atc_deploy
      vars: 
        provider: "{{ provider_atc }}"
        atc_service: Device
        atc_method: POST
        atc_declaration_file: "files/onboard_bigip_do_{{ item.atc_declaration_file }}.json"
        atc_delay: 15
        atc_retries: 40
      when: "{{ requested_modules == item.when }}"
      loop:
        - { atc_declaration_file: "ltm", when: "ltm" }
        - { atc_declaration_file: "asm", when: "asm" }


    ######################################################################################
    # Below tasks are for adding the BIG-IP to an existing role resource group on BIG-IQ #
    ######################################################################################

    - name: Authenticate to BIG-IQ
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/authn/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          loginProviderName: local
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    # Get BIG-IP's devicePermit selfLink used to append to an existing role's resource group
    - name: Get BIG-IP devicePermit selfLink
      uri:
        body: "{{ lookup('template', 'templates/device_permit.j2') }}"
        body_format: json
        headers:
          X-F5-Auth-Token: "{{ auth.json.token.token }}"
        method: POST
        status_code: 200,202
        url: "https://{{ mgmt }}/mgmt/cm/shared/device-permits"
        validate_certs: false
        timeout: 60
      register: device_permit_result
      delegate_to: localhost

    # Get just the selfLink and convert to list 
    - set_fact:
        device_permit_new: "{{ device_permit_result.selfLink | list }}"

    # Query for all application-creator-roles
    - name: Get all application-creator-roles
      uri:
        headers:
          X-F5-Auth-Token: "{{ auth.json.token.token }}"
        method: GET
        status_code: 200,202
        url: "https://{{ mgmt }}/mgmt/shared/authorization/application-creator-roles"
        validate_certs: false
        timeout: 60
      register: app_creator_role_list
      delegate_to: localhost

    # Get Role selfLink based on name provided by user
    - name: Get BIG-IQ Application Creator Role selfLink
      set_fact:
        custom_role: "{{ app_creator_role_list | json_query(query) }}"
      vars: 
        query: "json.items[?displayName=='{{ role_name }}'].selfLink"


    - name: Debug address
      debug: var=custom_role

    - name: Debug address
      debug: msg="{{ custom_role | regex_replace('localhost', mgmt) }}"

    # Get json of the application creator role and write the result to file
    - name: Get Application Creator Role
      uri:
        headers:
          X-F5-Auth-Token: "{{ auth.json.token.token }}"
        method: GET
        status_code: 200,202
        url: "{{ custom_role | regex_replace('localhost', mgmt) }}"
        validate_certs: false
        body_format: json
        timeout: 60
      register: app_creator_role_json
      delegate_to: localhost

    # - name: display app_creator_role.json file contents
    #   debug: var=item
    #   with_file:
    #     - "templates/app_creator_role.json"

    # - name: Install jq (json parser) package
    #   apt: name=jq state=present

    #Use below 4 tasks to modify just the devicePermitReferences list
    # Get existing devicePermitReferences list of the application creator role
    - name: Get existing devicePermitReferences list
      set_fact:
        device_permit_ref_existing: app_creator_role_json.devicePermitReferences

    # Append new BIG-IP devicePermit selfLink to devicePermitReferences list of the application creator role
    - name: Append new BIG-IP devicePermit selfLink to devicePermitReferences list 
      set_fact:
        device_permit_ref_new: "{{ device_permit_ref_existing +  device_permit_new }}"

    #Replace existing devicePermitReferences list with new one including new BIG-IP
    - name: Replace existing devicePermitReferences with new one
      set_fact:
        animals: "{{ animals|combine({'birds': {'cardinals': {'feathers': 'red'}}}, recursive=True) }}"

    #Update configuration of application creator role using the new config
