---
- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
    GCE_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"
    GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"

  tasks:

    - name: create a network
      gcp_compute_network:
          name: 'bigiq-lab-network-instance'
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: network

    - name: create a subnetwork
      gcp_compute_subnetwork:
        name: bigiq-lab-subnet
        region: "{{ gcp_region }}"
        network: "{{ network }}"
        ip_cidr_range: "{{ ip_cidr_range }}"
        project: "{{ GCE_PROJECT }}"
        state: present
      register: subnet

    - name: create a firewall
      gcp_compute_firewall:
        name: bigiq-lab-firewall
        network: "projects/{{ GCE_PROJECT }}/global/networks/{{ network.name }}"
        allowed:
        - ip_protocol: tcp
          ports: ['80','22','443']
        target_tags:
          - bigiq-lab
        source_ranges: ['0.0.0.0/0']
        project: "{{ GCE_PROJECT }}"
        state: present
      register: firewall

    - name: create an address
      gcp_compute_address:
          name: 'bigiq-lab-address-instance'
          region: "{{ gcp_region }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: address

    - name: Debug address
      debug: var=address

    - name: Set address as var
      set_fact:
        bigip_gcp_address: address.address

    - name: create a disk
      gcp_compute_disk:
          name: 'bigiq-lab-disk-instance'
          size_gb: 50
          source_image: 'projects/f5-7626-networks-public/global/images/f5-hourly-bigip-14-1-0-1-0-0-7-best-200mbps'
          zone: "{{ gcp_zone }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: disk

    - name: create an instance
      gcp_compute_instance:
          state: present
          name: bigiq-lab-bigip-instance
          machine_type: n1-standard-4
          disks:
            - auto_delete: true
              boot: true
              source: "{{ disk }}"
          network_interfaces:
              - network: "{{ network }}"
                access_configs:
                  - name: 'External NAT'
                    nat_ip: "{{ address }}"
                    type: 'ONE_TO_ONE_NAT'
          zone: "{{ gcp_zone }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          tags:
          items:
            - bigiq-lab
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ address.address }} port=22 delay=10 timeout=60