---

- name: TOWER-AS3-BIG-IQ - Debug
  hosts: tower
  connection: local
  gather_facts: false

  tasks:
    
    - name: Get setup facts
      setup:

    - name: show pwd
      command: pwd

    - name: Install roles from Ansible Galaxy
      command: ansible-galaxy install f5devcentral.atc_deploy -p ./roles/ 