---

- name: TOWER-AS3-BIG-IQ - Debug
  hosts: tower
  connection: local
  gather_facts: false

  tasks:
    
    - name: Debug playbook_dir path
      debug:
        var: "{{ playbook_dir }}"
    
    - name: Debug role_dir path
      debug:
        var: "{{ role_dir }}"