---
- name: TOWER-AS3-BIG-IQ - OFFBOARD AND DELETE BIG-IP from BIG-IQ
  hosts: bigiq
  connection: local
  gather_facts: false
  vars:
    GCE_PROJECT: "{{ lookup('env', 'GCE_PROJECT') }}"
    GCE_CREDENTIALS_FILE_PATH: "{{ lookup('env', 'GCE_CREDENTIALS_FILE_PATH') }}"
    GCE_EMAIL: "{{ lookup('env', 'GCE_EMAIL') }}"

  tasks:

    ############################################
    # Below tasks are for offboarding a BIG-IP #
    ############################################
    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    # provider var for atc_deploy role
    - set_fact:
        provider: 
          server: "{{ bigip_mgmt }}"
          server_port: 443
          user: "{{ bigip_user }}"
          password: "{{ bigip_password }}"
          validate_certs: false

    # Get authentication token for uri module tasks below
    - name: Authenticate to BIG-IQ
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/authn/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          loginProviderName: local
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

- name: Remove discovered device and its config
  bigiq_device_discovery:
    device_address: 192.168.1.1
    state: absent
    provider:
      password: secret
      server: lb.mydomain.com
      user: admin
  delegate_to: localhost

    # Discover new BIG-IP
    - name: Discover a new BIG-IP device
      bigiq_device_discovery:
        device_address: "{{ bigip_mgmt }}"

        modules: "{{ provisioned_modules }}"
        provider: 
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          server: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}"
          validate_certs: no
      delegate_to: localhost

    ################################################
    # Below tasks are for deleting a BIG-IP in GCP #
    ################################################

    # Create a 'custom' Network, as opposed to a legacy network created using gcp_compute_network
    - name: Create Custom Network
      gce_net:
        name: "{{ resource_prefix }}-network-instance"
        mode: custom
        credentials_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        service_account_email: "{{ GCE_EMAIL }}"
        subnet_name: bigiq-lab-subnet
        subnet_region: "{{ gcp_region }}"
        ipv4_range: "{{ ip_cidr_range }}"
        state: present
      register: gce_network

    - name: Open SSH and HTTPS ports in the GCE firewall
      gce_net:
        name: "{{ resource_prefix }}-network-instance"
        fwname: "fw-{{ resource_prefix }}-ssh-https"
        allowed: "tcp:22,443"
        target_tags:
          - bigiq-lab
        state: present
        src_range: 0.0.0.0/0
        service_account_email: "{{ GCE_EMAIL }}"
        credentials_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
        project_id: "{{ GCE_PROJECT }}"

    - name: create an address
      gcp_compute_address:
          name: '{{ resource_prefix }}-address-instance'
          region: "{{ gcp_region }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: address

    - name: Debug address
      debug: var=address

    - name: Set address as var
      set_fact:
        bigip_mgmt: address.address

    - name: create a disk
      gcp_compute_disk:
          name: '{{ resource_prefix }}-disk-instance'
          size_gb: 80
          source_image: 'projects/f5-7626-networks-public/global/images/f5-hourly-bigip-14-1-0-1-0-0-7-best-200mbps'
          zone: "{{ gcp_zone }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          state: present
      register: disk

    - name: create an instance
      gcp_compute_instance:
          state: present
          name: '{{ resource_prefix }}-bigip-instance'
          machine_type: n1-standard-4
          disks:
            - auto_delete: true
              boot: true
              source: "{{ disk }}"
          network_interfaces:
              - network: "{{ gce_network }}"
                access_configs:
                  - name: 'External NAT'
                    nat_ip: "{{ address }}"
                    type: 'ONE_TO_ONE_NAT'
          zone: "{{ gcp_zone }}"
          project: "{{ GCE_PROJECT }}"
          auth_kind: serviceaccount
          service_account_file: "{{ GCE_CREDENTIALS_FILE_PATH }}"
          scopes:
            - https://www.googleapis.com/auth/compute
          metadata:
            enable-oslogin: "FALSE"
          tags:
            items:
              - bigiq-lab
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ address.address }} port=22 delay=10 timeout=60

