---
- name: TOWER-AS3-BIG-IQ - Onboard Tenant
  hosts: bigiq
  connection: local
  gather_facts: false

  tasks:

    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    - name: Authenticate to BIG-IQ
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/authn/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          loginProviderName: local
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    # Confirm existing list of BIG-IQ users
    - name: Confirm existing BIG-IQ users 
      uri:
        headers:
          X-F5-Auth-Token: "{{ auth.json.token.token }}"
        method: GET
        status_code: 200,202
        url: "https://{{ mgmt }}/mgmt/shared/authz/users"
        validate_certs: false
        timeout: 60
      register: user_list
      delegate_to: localhost

    - debug:
        var: user_list
    
    - debug:
        var: user_name

    - name: Get BIG-IQ user
      set_fact:
        new_user_exists: "{{ item.name }}"
      with_items:
        "{{ user_list.json.items | json_query(query) }}"
      vars: 
        query: "[?name=='{{ user_name }}'].{name: name}"

    - debug:
        var: "{{ new_user_exists }}"

    - name: Create a new user 
      uri:
        body: "{{ lookup('template', 'templates/user_create.j2') }}"
        body_format: json
        headers:
          X-F5-Auth-Token: "{{ auth.json.token.token }}"
        method: POST
        status_code: 200,202
        url: "https://{{ mgmt }}/mgmt/shared/authz/users"
        validate_certs: false
        timeout: 60
      register: user_status
      delegate_to: localhost
      when: new_user_exists is undefined

    - name: Add new user to existing role
      uri:
        body: "{{ lookup('template', 'templates/role_associate.j2') }}"
        body_format: json
        headers:
          X-F5-Auth-Token: "{{ auth.json.token.token }}"
        method: PATCH
        status_code: 200,202
        url: "https://{{ mgmt }}/mgmt/shared/authorization/roles/a11e7dd6-235d-38e8-b8a4-39995626e3ac"
        validate_certs: false
        timeout: 60
      register: user_status
      delegate_to: localhost

    # This variable will be used later on to add to list of users that can use the Tower Templates
    - set_fact:
        new_user: "{{ user_name }}"
