---
- name: TOWER-AS3-BIG-IQ - ONBOARD BIG-IP on BIG-IQ USING DO
  hosts: bigiq
  connection: local
  gather_facts: false

  tasks:
    # First download galaxy roles for F5 ATC
    - name: Install roles from Ansible Galaxy
      command: ansible-galaxy install f5devcentral.atc_deploy -p ./roles/ 

    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    # provider var for atc_deploy role
    - set_fact:
        provider: 
          server: "{{ bigip_mgmt }}"
          server_port: 443
          user: "{{ bigip_user }}"
          password: "{{ bigip_password }}"
          validate_certs: false

    # Use DO to license, provision, and set passwords on new BIG-IP
    # Official galaxy role for F5 automation tool chain (https://galaxy.ansible.com/f5devcentral/atc_deploy)
    - name: ATC POST
      include_role:
        name: atc_deploy
      vars: 
        provider: "{{ provider }}"
        atc_service: Device
        atc_method: POST
        atc_declaration_file: "{{ lookup('template', 'templates/onboard_bigip_do_{{ item.atc_declaration_file }}.j2') }}"
        atc_delay: 10
        atc_retries: 5
      when: "{{ requested_modules == item.when }}"
      loop:
        - { atc_declaration_file: "ltm", when: "ltm" }
        - { atc_declaration_file: "asm", when: "waf" }

    # Get authentication token for uri module tasks below
    - name: Authenticate to BIG-IQ
      uri:
        url: "https://{{ mgmt }}/mgmt/shared/authn/login"
        method: POST
        headers:
          Content-Type: application/json
        body:
          username: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          loginProviderName: local
        body_format: json
        timeout: 60
        status_code: 200, 202
        validate_certs: false
      register: auth

    # By default, LTM is provisioned, so adding to the list of modules to discover when registering on BIG-IQ.
    # Also adding in GTM  
    - set_fact:
        provisioned_modules: ['ltm', 'gtm']

    # Note that security_shared is also required here
    - name: Add ASM to list of modules to discover
      set_fact:
        provisioned_modules: "{{ provisioned_modules + ['asm'] + ['security_shared']}}"
      when: requested_modules == "asm"

    - name: Debug provisioned_modules list
      debug: var=provisioned_modules

    # Discover new BIG-IP
    - name: Discover a new BIG-IP device
      bigiq_device_discovery:
        device_address: "{{ bigip_mgmt }}"
        device_username: "{{ bigip_user }}"
        device_password: "{{ bigip_password }}"
        modules: "{{ provisioned_modules }}"
        provider: 
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          server: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}"
          validate_certs: no
      delegate_to: localhost