---
- name: TOWER-AS3-BIG-IQ - ASSIGN REGKEY TO MANAGED BIGIP, BY NAMEß
  hosts: bigiq
  connection: local
  gather_facts: false

  tasks:

    - name: Register a managed device, by name
      bigiq_regkey_license_assignment:
        pool: "{{ regkey_pool_name }}"
        key: "{{ regkey }}"
        device: "{{ bigip_name }}"
        managed: yes
        state: present
        provider:
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          server: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}"
          validate_certs: no
      delegate_to: localhost