---
- name: TOWER-AS3-BIG-IQ - REGKEY POOL
  hosts: bigiq
  connection: local
  gather_facts: false

  tasks:

    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    - debug:
        var: regkey_pool_name 

    - name: Create a registration key (regkey) pool to hold individual device licenses
      bigiq_regkey_pool:
        name: regkey_pool_name
        state: present
        description: "NSSOL Regkey Pool"
        provider: 
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          server: "{{ mgmt }}"
          validate_certs: no
      delegate_to: localhost
