---
- name: TOWER-AS3-BIG-IQ - REGKEY POOL
  hosts: bigiq
  connection: local
  gather_facts: false

  tasks:

    - set_fact:
        mgmt: "{{ hostvars[inventory_hostname]['mgmt_ip'] }}:{{ hostvars[inventory_hostname]['mgmt_port'] }}"

    - name: Add a registration key license to a pool
      bigiq_regkey_license:
        regkey_pool: "{{ regkey_pool_name }}"
        license_key: "{{ regkey }}"
        accept_eula: yes
        provider: 
          user: "{{ bigiq_user }}"
          password: "{{ bigiq_pass }}"
          server: "{{ mgmt }}"
      delegate_to: localhost
